#!/bin/sh
set -eu
dest=
for arg in "$@"; do dest=$arg; done
case "$dest" in
  *.ompup-backup-*)
    if [ -n "${OMPUP_FAKE_MV_MUTATE_BEFORE_BACKUP:-}" ]; then
      printf 'concurrent\n' > "$OMPUP_FAKE_MV_MUTATE_BEFORE_BACKUP"
    fi
    /bin/mv "$@"
    [ "${OMPUP_FAKE_MV_FAIL_AFTER_BACKUP:-0}" != 1 ] || exit 99
    exit 0 ;;
esac
exec /bin/mv "$@"
